### ISSUE TITLE
about threshold is 0

### ISSUE THREAD

**Issue by gaoqiang19514** [CassetteRocks/react-infinite-scroller#164] opened 2018-07-06 11:54 UTC
**Describe the bug**
when threshold={ 0 } , loadMore function will not call, so i think `offset <= Number(this.props.threshold) ` can resolve this problem

**Comment by danbovey** [comment] 2018-07-06 11:56
Hi. I remember answering this before... see my answer to #52.

Duplicate of #52

**Closed by danbovey** 2018-07-06 11:56 UTC
